DROP TABLE IF EXISTS JT.Image_Label_Scores;
CREATE TABLE JT.Image_Label_Scores (
        ApplicationId TEXT,
        Created TIMESTAMP,
        ImageFileName TEXT,
        Score_One NUMERIC,
        Desc_One TEXT,
        Score_Two NUMERIC,
        Desc_Two TEXT,
        Score_Three NUMERIC,
        Desc_Three TEXT,
        Score_Four NUMERIC,
        Desc_Four TEXT,
        Score_Five NUMERIC,
        Desc_Five TEXT,
        Score_Six NUMERIC,
        Desc_Six TEXT,
        Score_Seven NUMERIC,
        Desc_Seven TEXT,
        Score_Eight NUMERIC,
        Desc_Eight TEXT,
        Score_Nine NUMERIC,
        Desc_Nine TEXT,
        Score_Ten NUMERIC,
        Desc_Ten TEXT
);   